### ISSUE TITLE
Question: Stale OTP code

### ISSUE THREAD

**Issue by Xdomen** [itsautomic/robotframework-otp#1]
Hey!

First of all, thank you for providing this solution for robot framework. 

We have encounter an issue where OTP is getting calculated accordingly for the first test, however after 35 seconds we are generating it again in another robotframework test and it's getting the same OTP code constantly. It doesn't update after 35 seconds. If we restart the tests it gets generated correctly.  

We made sure to use different variables for calculating OTP, and somehow we can't resolve the issue. Any idea what could cause the issue? 

Thank you for all your help in advance. Highly appreciated!

**Comment by Xdomen** [comment]
We managed to resolve the issue by changing
`return totp.at(timestamp)` to `return totp.now()` in https://github.com/FormulatedAutomation/robotframework-otp/blob/master/src/OTP/otp.py Otherwise it returned the same OTP code :)

**Comment by mdp** [comment]
Thanks for reporting this. Looking to fix it in #2

**Comment by mdp** [comment]
This is fixed in 1.0.2 on PyPi. Thanks for taking the time to report this issue.
